### ISSUE TITLE
get translations for arabic and persian/farsi

### ISSUE THREAD

**Issue by mattl** [creativecommons/sotc-2015#60]
These aren't in text in the report, only as bitmap images so I can't copy it like I did with the others. I need text for the web version.

**Comment by janetpkr** [comment]
Naeema sent this on cc-affiliates thread, titled Arabic and Persian -- so Arabic first.
![arabic-and-persian](https://cloud.githubusercontent.com/assets/6394777/11633636/40ba8d32-9cc1-11e5-8a04-8355cdb69bab.png)

The original file she said:

"The Arabic & Persian are segmented and in reverse: العربية - فارسي 
Page 7 - I can send them to you in jpg or png format to include as images so they dont get flipped due to design program not supporting the languages "

Wrong original version:
![arabic and persian wrong](https://cloud.githubusercontent.com/assets/6394777/11633671/671ce6b4-9cc1-11e5-9909-e10c10314045.png)

**Comment by mattl** [comment]
So العربية is Arabic and فارسي is Farsi?

**Comment by janetpkr** [comment]
yes

@NaeemaZarif
